### ISSUE TITLE
[bug] generate icons fail

### ISSUE THREAD

**Issue by wtjperi2003** [tauri-apps/tauricon#78]
### Describe the bug

run script 'npx @tauri-apps/tauricon --help' will show intall @tauri-apps/tauricon every time even I have installed
![微信截图_20220812170126](https://user-images.githubusercontent.com/10322892/184322197-1c4076a3-4920-41c3-a678-49b2a47ad458.png)

### Platform and versions

Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 104.0.1293.47
  › MSVC: 
      - Visual Studio ���ɹ��� 2019
      - Visual Studio ���ɹ��� 2022
  › Node.js: 16.14.2
  › npm: 8.5.0
  › pnpm: 6.32.3
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js

App directory structure
  ├─ dist
  ├─ env
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by alfreddagenais** [comment]
Same bug for me to! Weird. 

I just saw this link explain a bit why https://stackoverflow.com/a/58642519/12932615

---

**Update**: I finaly solve the issue for me. 

I have try to install normally the package with `npx @tauri-apps/tauricon`, and I try and retry, without any errors

I try to install into my local repository the package. `yarn add @tauri-apps/tauricon`. And I just got an Error : 
![Capture-2022-08-19_23-00-01-000505](https://user-images.githubusercontent.com/5769264/185726720-9c9458a3-6a31-45ce-9163-eee45fe833f0.png)

`'vips/vips8' file not found`... Hum so I search for this. And I found, I need to install a package for me.

I follow instructions on : https://github.com/libvips/libvips/wiki/Build-for-macOS with the command 

`brew install vips`

Now I have the vips package
![Capture-2022-08-19_23-01-52-000506@2x](https://user-images.githubusercontent.com/5769264/185726808-bb5a1735-fcde-484e-a292-6e9399fa5c04.png)

I try again the command `npx @tauri-apps/tauricon` and now All good for me.

![Capture-2022-08-19_23-13-16-000507@2x](https://user-images.githubusercontent.com/5769264/185726870-a834b1d6-7da7-4b06-8095-60df2f136b62.png)

Enjoy this awnser help you guys! 👍

**Comment by FabianLars** [comment]
> every time even I have installed

That's a weirdness with npx i couldn't figure out how to fix, but we won't look into fixing it because the rust rewrite is complete and will be part of tauri 1.1

Also this alone doesn't cause the generation to fail (which this issue's title is about), we'd need more info about it to help, but this doesn't seem to be a common issue _and_ again, the rust rewrite is just around the corner (you could try it out right now if you want by following the instructions i posted in #79)
