### ISSUE TITLE
need to specify --target for the icons to be placed in the correct place

### ISSUE THREAD

**Issue by Megamannen** [tauri-apps/tauricon#9]
When only running ```tauricon``` the icons get placed in no-mans-land. 
I can investigate this further, just want to register this so I don't forget it.

Linux
fish shell

To get the correct behaviour I need to do
```bash
tauricon --target ./src-tauri/icons
```

**Comment by FabianLars** [comment]
Did you install tauricon globally or locally? If globally i wonder why it didn't crash, because it actively looks for a tauri.conf file

**Comment by Megamannen** [comment]
locally, now I've verified this.

```
Linux spectre 5.17.0-1-MANJARO #1 SMP PREEMPT Mon Mar 7 08:29:54 UTC 2022 x86_64 GNU/Linux

node --version
v14.19.1
```

This gives no icons (have not searched for the icons, but they are not in the project folder at least)
Simple setup to reproduce
(you need to have app-icon.png in the folder of course)
```bash
yarn add -D @tauri-apps/tauricon:github:tauri-apps/tauricon
mkdir -p src-tauri/icons
npx tauricon
```

But if you instead run it like this it works
```bash
npx tauricon --target src-tauri/icons
```
